import type { Metadata } from 'next';
import { BMJUA } from '@/modules/font';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/pages/api/auth/[...nextauth]';

import Navbar from '@/components/Navbar';

import './globals.css';
import { NextAuthProvider } from '@/components/provider/NextAuthProvider';

import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';

config.autoAddCss = false;

export const metadata: Metadata = {
  title: '오늘 뭐 봐?',
  description: 'Generated by create next app',
};

/**
 * /app의 최상위 컴포넌트
 */
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang='ko' className='white'>
      <body className={BMJUA.className}>
        <NextAuthProvider session={session}>
          <Navbar session={session} />
          {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}
