import type { Metadata } from 'next';
import { BMJUA } from '@/modules/font';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/pages/api/auth/[...nextauth]';

import Navbar from '@/components/Navbar';

import './globals.css';

export const metadata: Metadata = {
  title: '오늘 뭐 봐?',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang='ko' className='white'>
      <body className={BMJUA.className}>
        <Navbar session={session} />
        {children}
      </body>
    </html>
  );
}
