import type { Metadata } from 'next';
import { BMJUA } from '@/modules/font';

import Navbar from '@/components/Navbar';

import './globals.css';

import { auth } from '@/auth';
import AuthSession from '@/components/provider/AuthSession';

import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
import AlertProvider from '@/components/context/Alert-Context';
import Alert from '@/components/Alert';

config.autoAddCss = false;

export const metadata: Metadata = {
  title: '오늘 뭐 봐?',
  description: 'Generated by create next app',
};

/**
 * /app의 최상위 컴포넌트
 */
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang='ko' className='white'>
      <body className={BMJUA.className}>
        <AlertProvider>
          <AuthSession>
            <Alert />
            <Navbar session={session} />
            {children}
          </AuthSession>
        </AlertProvider>
      </body>
    </html>
  );
}
